//
// .swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct : Codable { 


    public var id: String
    public var principalName: Null
    public var displayName: Null
    public var smtpAddress: Null

    public init(id: String, principalName: Null, displayName: Null, smtpAddress: Null) {
        self.id = id
        self.principalName = principalName
        self.displayName = displayName
        self.smtpAddress = smtpAddress
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id = "Id"
        case principalName = "PrincipalName"
        case displayName = "DisplayName"
        case smtpAddress = "SmtpAddress"
    }

}
