//
// News.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct News: Codable { 


    public var news: String
    public var id: Int
    public var theme: String
    public var date: String

    public init(news: String, id: Int, theme: String, date: String) {
        self.news = news
        self.id = id
        self.theme = theme
        self.date = date
    }

}
