//
// TodoItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TodoItem: Codable, Identifiable { 


    public var dueDateTimeZone: String
    public var bodyLastModifiedTime: String
    public var reminderType: String
    public var createdByUserId: String
    public var dueDateTime: String
    public var id: String
    public var reminderIsSnoozed: Bool
    public var completedDateTime: String
    public var createdByUserSmtpAddress: String
    public var isReminderOn: Bool
    public var postponedDay: String
    public var recurrenceType: String
    public var lastModifiedDateTime: String
    public var subject: String
    public var reminderDateTimeZone: String
    public var createdByRequestId: String
    public var importance: String
    public var completingWillTriggerAnotherRecurrence: String
    public var dueDate: String
    public var completedByUserId: String
    public var reminderSnoozeTimeInMinutes: String
    public var isIgnored: Bool
    public var linkedEntities: String
    public var changeKey: String
    public var createdWithLocalId: String
    public var createdByUserPrincipalName: String
    public var isImported: Bool
    public var reminderPerson: String
    public var createdByUserDisplayName: String
    public var source: String
    public var status: String
    public var committedDay: String
    public var reminderDateTime: String
    public var reminderTimezone: String
    public var deltaLink: String
    public var bodyContentType: String
    public var reminderGeoFence: String
    public var createdDateTime: String
    public var sensitivity: String
    public var committedOrder: String
    public var allExtensions: [String]
    public var categories: [String]
    public var completedByUserDisplayName: String
    public var parentFolderId: String
    public var orderDateTime: String
    public var bodyContent: String
    public var reminderReminderDateTime: String

    public init(dueDateTimeZone: String, bodyLastModifiedTime: String, reminderType: String, createdByUserId: String, dueDateTime: String, id: String, reminderIsSnoozed: Bool, completedDateTime: String, createdByUserSmtpAddress: String, isReminderOn: Bool, postponedDay: String, recurrenceType: String, lastModifiedDateTime: String, subject: String, reminderDateTimeZone: String, createdByRequestId: String, importance: String, completingWillTriggerAnotherRecurrence: String, dueDate: String, completedByUserId: String, reminderSnoozeTimeInMinutes: String, isIgnored: Bool, linkedEntities: String, changeKey: String, createdWithLocalId: String, createdByUserPrincipalName: String, isImported: Bool, reminderPerson: String, createdByUserDisplayName: String, source: String, status: String, committedDay: String, reminderDateTime: String, reminderTimezone: String, deltaLink: String, bodyContentType: String, reminderGeoFence: String, createdDateTime: String, sensitivity: String, committedOrder: String, allExtensions: [String], categories: [String], completedByUserDisplayName: String, parentFolderId: String, orderDateTime: String, bodyContent: String, reminderReminderDateTime: String) {
        self.dueDateTimeZone = dueDateTimeZone
        self.bodyLastModifiedTime = bodyLastModifiedTime
        self.reminderType = reminderType
        self.createdByUserId = createdByUserId
        self.dueDateTime = dueDateTime
        self.id = id
        self.reminderIsSnoozed = reminderIsSnoozed
        self.completedDateTime = completedDateTime
        self.createdByUserSmtpAddress = createdByUserSmtpAddress
        self.isReminderOn = isReminderOn
        self.postponedDay = postponedDay
        self.recurrenceType = recurrenceType
        self.lastModifiedDateTime = lastModifiedDateTime
        self.subject = subject
        self.reminderDateTimeZone = reminderDateTimeZone
        self.createdByRequestId = createdByRequestId
        self.importance = importance
        self.completingWillTriggerAnotherRecurrence = completingWillTriggerAnotherRecurrence
        self.dueDate = dueDate
        self.completedByUserId = completedByUserId
        self.reminderSnoozeTimeInMinutes = reminderSnoozeTimeInMinutes
        self.isIgnored = isIgnored
        self.linkedEntities = linkedEntities
        self.changeKey = changeKey
        self.createdWithLocalId = createdWithLocalId
        self.createdByUserPrincipalName = createdByUserPrincipalName
        self.isImported = isImported
        self.reminderPerson = reminderPerson
        self.createdByUserDisplayName = createdByUserDisplayName
        self.source = source
        self.status = status
        self.committedDay = committedDay
        self.reminderDateTime = reminderDateTime
        self.reminderTimezone = reminderTimezone
        self.deltaLink = deltaLink
        self.bodyContentType = bodyContentType
        self.reminderGeoFence = reminderGeoFence
        self.createdDateTime = createdDateTime
        self.sensitivity = sensitivity
        self.committedOrder = committedOrder
        self.allExtensions = allExtensions
        self.categories = categories
        self.completedByUserDisplayName = completedByUserDisplayName
        self.parentFolderId = parentFolderId
        self.orderDateTime = orderDateTime
        self.bodyContent = bodyContent
        self.reminderReminderDateTime = reminderReminderDateTime
    }

}
