//
// Versions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Versions: Codable, Identifiable { 


    public var date: String
    public var id: String
    public var updateContent: String
    public var version: String

    public init(date: String, id: String, updateContent: String, version: String) {
        self.date = date
        self.id = id
        self.updateContent = updateContent
        self.version = version
    }

}
